module main_2;

void main() {
    throw new Exception("There has been an error.");
}
